# Generated by Django 4.1.1 on 2023-01-22 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_artist_genre_audio_artist_audio_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audios.artist')),
            ],
        ),
    ]
