# Generated by Django 4.1.1 on 2023-01-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0005_remove_audio_author_audio_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='image_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
